name: Run shell checks

on:
  push:
    paths:
      - .github/workflows/*.yml

jobs:
  checks:
    name: Shell checks
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: 'this'
      - name: Checkout labs
        uses: actions/checkout@v3
        with:
          repository: 'devnull-cz/unix-linux-prog-in-c-labs'
          path: 'labs'
      - name: Checkout STEF
        uses: actions/checkout@v3
        with:
          repository: 'devnull-cz/stef'
          path: 'stef'
      - name: Compile
        run: cd this && make && cp mysh /tmp
      - name: Create test configuration
        run: cp this/test-config.local labs/final-assignment-tests/shell
      - name: Run the tests
        run: cd final-assignment-tests/shell && ./run-tests.sh
