name: Run shell checks

on:
  push:
    paths:
      - .github/workflows/*.yml

jobs:
  checks:
    name: Shell checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'devnull-cz/unix-linux-prog-in-c-labs'
          path: 'stef'
      - name: Checkout STEF
        uses: actions/checkout@v3
        with:
          repository: 'devnull-cz/stef'
          path: 'stef'
      - name: Compile
        run: echo gcc mysh.c
      - name: Create test configuration
        run: echo foo
      - name: Run the tests
        run: pwd
